spring:
  application:
    name: wanted-pre-onboarding-backend

  server:
    port: 8080

  datasource:
    url: jdbc:mysql://${DATABASE_URL}
    password: ${DATABASE_PW}
    username: ${DATABASE_ID}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100

  sql:
    init:
      mode: always
